ABALONE = "abalone"
LOBSTER = "lobster"
QUARTER = "quarter"
SQUARE = "square"
INCHES = "inches"
MM = "mm"

DEF_SQUARE_SIZE_IN = 2.0
DEF_SQUARE_SIZE_MM = 50.8

QUARTER_SIZE_IN = 0.955
QUARTER_SIZE_MM = 24.26

REF_TYPES = [ABALONE, QUARTER, SQUARE]
REF_UNITS = [INCHES, MM]