ABALONE = "abalone"
LOBSTER = "lobster"
SCALLOP = "scallop"

QUARTER = "quarter"
SQUARE = "square"
INCHES = "inches"
MM = "mm"

MIN_SIZE = 1.0
MAX_SIZE = 15.0


DEF_SQUARE_SIZE_IN = 2.0
DEF_SQUARE_SIZE_MM = 50.8

QUARTER_SIZE_IN = 0.955
QUARTER_SIZE_MM = 24.26

INCHES_TO_MM = 25.4;

REF_TYPES = [ABALONE, QUARTER, SQUARE]
REF_UNITS = [INCHES, MM]