name: ocean-ruler-python-fastai
channels:
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/pro
  - defaults
dependencies:
  - python=3.6.2
  - pip>21
  - pip:
    - tables==3.4.3
    - msgpack==0.6.1
    - mkl-random==1.0.1
    - mkl-fft==1.0.0.17
  - navigator-updater=0.2.1
  - blaze=0.11.3
  - clyent=1.2.2
  - llvmlite=0.23.1
  - bokeh=0.12.16
  - bkcharts=0.2
  - certifi=2018.4.16
  - dask=0.17.5
  - cytoolz=0.9.0.1
  - cloudpickle=0.5.3
  - click=6.7
  - datashape=0.5.4
  - Jinja2=2.10
  - itsdangerous=0.24
  - PyYAML=3.12
  - locket=0.2.0
  - partd=0.3.8
  - MarkupSafe=1.0
  - distributed=1.21.8
  - odo=0.5.1
  - pyparsing=2.2.0
  - tblib=1.3.2
  - decorator=4.3.0
  - Flask=1.0.2
  - Flask-Cors=3.0.4
  - h5py=2.7.1
  - heapdict=1.0.0
  - msgpack-python=0.5.6
  - multipledispatch=0.5.0
  - networkx=2.1
  - numba=0.38.0
  - numexpr=2.6.5
  - numpy=1.14.3
  - packaging=17.1
  - pandas=0.23.0
  - psutil=5.4.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - QtPy=1.4.1
  - requests=2.18.4
  - six=1.11.0
  - sortedcontainers=1.5.10
  - SQLAlchemy=1.2.7
  - toolz=0.9.0
  - tornado=5.0.2
  - urllib3=1.22
  - Werkzeug=0.14.1
  - zict=0.1.3
  - asn1crypto=0.24.0
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.2.2
  - idna=2.6
  - pycparser=2.18
  - pyOpenSSL=18.0.0
  - PySocks=1.6.8
  - Cython=0.28.2